In [9]:
import pandas as pd

In [16]:
junedata = pd.read_csv("202006-citibike-tripdata.csv/202006-citibike-tripdata.csv")
maydata = pd.read_csv("202005-citibike-tripdata.csv/202005-citibike-tripdata.csv")
aprildata = pd.read_csv("202004-citibike-tripdata.csv/202004-citibike-tripdata.csv")

In [17]:
print (maydata.head(5))

   tripduration                 starttime                  stoptime  \
0           336  2020-05-01 00:01:06.3380  2020-05-01 00:06:42.9560
1           853  2020-05-01 00:01:08.1950  2020-05-01 00:15:21.2150
2            78  2020-05-01 00:01:08.5260  2020-05-01 00:02:27.0490
3          1185  2020-05-01 00:02:22.4380  2020-05-01 00:22:08.1220
4           272  2020-05-01 00:02:32.8280  2020-05-01 00:07:05.0880

   start station id                  start station name  \
0              2017                     E 43 St & 2 Ave
1              3376                     E 65 St & 2 Ave
2               396          Lefferts Pl & Franklin Ave
3              3630  Frederick Douglass Blvd & W 115 St
4              3776          Central Ave & Starr Street

   start station latitude  start station longitude  end station id  \
0               40.750224               -73.971214             465
1               40.764719               -73.962221             478
2               40.680342               -73.955769            3789
3               40.803865               -73.955931            3506
4               40.700003               -73.928340            3068

           end station name  end station latitude  end station longitude  \
0        Broadway & W 41 St             40.755136             -73.986580
1          11 Ave & W 41 St             40.760301             -73.998842
2     Fulton St & Irving Pl             40.681860             -73.959432
3  Lexington Ave & E 120 St             40.801307             -73.939817
4    Humboldt St & Varet St             40.703172             -73.940636

   bikeid    usertype  birth year  gender
0   18015  Subscriber        1993       1
1   35905  Subscriber        1989       1
2   33350  Subscriber        1938       2
3   43790  Subscriber        1996       1
4   39912  Subscriber        1993       1

In [22]:
junedf = pd.DataFrame(data = junedata)
maydf = pd.DataFrame(data = maydata)
aprildf = pd.DataFrame(data = aprildata)

In [29]:
aprildf

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,534,2020-04-01 00:00:15.2800,2020-04-01 00:09:09.8730,3656,E 2 St & Avenue A,40.723077,-73.985836,545,E 23 St & 1 Ave,40.736502,-73.978095,15162,Subscriber,1990,2
1,529,2020-04-01 00:02:28.9430,2020-04-01 00:11:18.3410,3163,Central Park West & W 68 St,40.773407,-73.977825,3301,Columbus Ave & W 95 St,40.791956,-73.968087,42861,Subscriber,1974,1
2,1488,2020-04-01 00:02:56.0900,2020-04-01 00:27:44.2530,3164,Columbus Ave & W 72 St,40.777057,-73.978985,3605,31 Ave & Crescent St,40.765835,-73.926547,35989,Subscriber,1982,1
3,341,2020-04-01 00:03:25.1410,2020-04-01 00:09:06.3190,3827,Halsey St & Broadway,40.685650,-73.915640,3869,Van Buren St & Broadway,40.692000,-73.926170,37548,Subscriber,1996,1
4,2206,2020-04-01 00:05:35.2790,2020-04-01 00:42:21.9080,3890,Grove St & Broadway,40.690470,-73.923511,3058,Lewis Ave & Kosciuszko St,40.692371,-73.937054,39701,Subscriber,1977,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
682757,1680,2020-04-30 23:59:00.7780,2020-05-01 00:27:01.7600,447,8 Ave & W 52 St,40.763707,-73.985162,2021,W 45 St & 8 Ave,40.759291,-73.988597,43888,Subscriber,1989,1
682758,1334,2020-04-30 23:59:23.6460,2020-05-01 00:21:38.2190,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,36853,Subscriber,1973,1
682759,1334,2020-04-30 23:59:33.6760,2020-05-01 00:21:48.2150,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,37808,Subscriber,1981,1
682760,234,2020-04-30 23:59:56.9720,2020-05-01 00:03:51.9600,469,Broadway & W 53 St,40.763441,-73.982681,495,W 47 St & 10 Ave,40.762699,-73.993012,20635,Subscriber,1996,2
682761,267,2020-04-30 23:59:59.3510,2020-05-01 00:04:26.8110,3812,University Pl & E 14 St,40.734814,-73.992085,503,E 20 St & Park Ave,40.738274,-73.987520,37530,Subscriber,1980,1

In [26]:
trip_df = junedf.append(maydf, ignore_index=True)

In [27]:
trip_df = trip_df.append(aprildf, ignore_index=True)

In [28]:
trip_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2
1,3810,2020-06-01 00:00:03.5530,2020-06-01 01:03:33.9360,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,336,Sullivan St & Washington Sq,40.730477,-73.999061,37558,Subscriber,1969,0
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2
3,226,2020-06-01 00:00:12.1780,2020-06-01 00:03:58.8640,3255,8 Ave & W 31 St,40.750585,-73.994685,505,6 Ave & W 33 St,40.749013,-73.988484,39674,Customer,1969,0
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4052920,1680,2020-04-30 23:59:00.7780,2020-05-01 00:27:01.7600,447,8 Ave & W 52 St,40.763707,-73.985162,2021,W 45 St & 8 Ave,40.759291,-73.988597,43888,Subscriber,1989,1
4052921,1334,2020-04-30 23:59:23.6460,2020-05-01 00:21:38.2190,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,36853,Subscriber,1973,1
4052922,1334,2020-04-30 23:59:33.6760,2020-05-01 00:21:48.2150,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,37808,Subscriber,1981,1
4052923,234,2020-04-30 23:59:56.9720,2020-05-01 00:03:51.9600,469,Broadway & W 53 St,40.763441,-73.982681,495,W 47 St & 10 Ave,40.762699,-73.993012,20635,Subscriber,1996,2
4052924,267,2020-04-30 23:59:59.3510,2020-05-01 00:04:26.8110,3812,University Pl & E 14 St,40.734814,-73.992085,503,E 20 St & Park Ave,40.738274,-73.987520,37530,Subscriber,1980,1

In [30]:
trip_df['age'] = 2020 - trip_df['birth year']

In [31]:
trip_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,age
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2,23
1,3810,2020-06-01 00:00:03.5530,2020-06-01 01:03:33.9360,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,336,Sullivan St & Washington Sq,40.730477,-73.999061,37558,Subscriber,1969,0,51
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2,32
3,226,2020-06-01 00:00:12.1780,2020-06-01 00:03:58.8640,3255,8 Ave & W 31 St,40.750585,-73.994685,505,6 Ave & W 33 St,40.749013,-73.988484,39674,Customer,1969,0,51
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4052920,1680,2020-04-30 23:59:00.7780,2020-05-01 00:27:01.7600,447,8 Ave & W 52 St,40.763707,-73.985162,2021,W 45 St & 8 Ave,40.759291,-73.988597,43888,Subscriber,1989,1,31
4052921,1334,2020-04-30 23:59:23.6460,2020-05-01 00:21:38.2190,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,36853,Subscriber,1973,1,47
4052922,1334,2020-04-30 23:59:33.6760,2020-05-01 00:21:48.2150,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,37808,Subscriber,1981,1,39
4052923,234,2020-04-30 23:59:56.9720,2020-05-01 00:03:51.9600,469,Broadway & W 53 St,40.763441,-73.982681,495,W 47 St & 10 Ave,40.762699,-73.993012,20635,Subscriber,1996,2,24
4052924,267,2020-04-30 23:59:59.3510,2020-05-01 00:04:26.8110,3812,University Pl & E 14 St,40.734814,-73.992085,503,E 20 St & Park Ave,40.738274,-73.987520,37530,Subscriber,1980,1,40

In [34]:
age_under65 = trip_df['age'] <= 65

In [35]:
print(age_under65.head())

0    True
1    True
2    True
3    True
4    True
Name: age, dtype: bool

In [36]:
trip_df = trip_df[age_under65]

In [37]:
trip_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,age
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2,23
1,3810,2020-06-01 00:00:03.5530,2020-06-01 01:03:33.9360,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,336,Sullivan St & Washington Sq,40.730477,-73.999061,37558,Subscriber,1969,0,51
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2,32
3,226,2020-06-01 00:00:12.1780,2020-06-01 00:03:58.8640,3255,8 Ave & W 31 St,40.750585,-73.994685,505,6 Ave & W 33 St,40.749013,-73.988484,39674,Customer,1969,0,51
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4052920,1680,2020-04-30 23:59:00.7780,2020-05-01 00:27:01.7600,447,8 Ave & W 52 St,40.763707,-73.985162,2021,W 45 St & 8 Ave,40.759291,-73.988597,43888,Subscriber,1989,1,31
4052921,1334,2020-04-30 23:59:23.6460,2020-05-01 00:21:38.2190,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,36853,Subscriber,1973,1,47
4052922,1334,2020-04-30 23:59:33.6760,2020-05-01 00:21:48.2150,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,37808,Subscriber,1981,1,39
4052923,234,2020-04-30 23:59:56.9720,2020-05-01 00:03:51.9600,469,Broadway & W 53 St,40.763441,-73.982681,495,W 47 St & 10 Ave,40.762699,-73.993012,20635,Subscriber,1996,2,24
4052924,267,2020-04-30 23:59:59.3510,2020-05-01 00:04:26.8110,3812,University Pl & E 14 St,40.734814,-73.992085,503,E 20 St & Park Ave,40.738274,-73.987520,37530,Subscriber,1980,1,40

In [39]:
gender_12 = trip_df['gender'] != 0

In [40]:
print(gender_12.head())

0     True
1    False
2     True
3    False
4     True
Name: gender, dtype: bool

In [42]:
trip_df = trip_df[gender_12]

In [43]:
trip_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,age
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2,23
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2,32
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2,23
5,355,2020-06-01 00:00:22.6500,2020-06-01 00:06:18.5250,248,Laight St & Hudson St,40.721854,-74.007718,247,Perry St & Bleecker St,40.735354,-74.004831,39594,Subscriber,1990,1,30
7,1810,2020-06-01 00:00:27.5880,2020-06-01 00:30:38.2560,3263,Cooper Square & Astor Pl,40.729515,-73.990753,496,E 16 St & 5 Ave,40.737262,-73.992390,16571,Customer,1995,2,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4052920,1680,2020-04-30 23:59:00.7780,2020-05-01 00:27:01.7600,447,8 Ave & W 52 St,40.763707,-73.985162,2021,W 45 St & 8 Ave,40.759291,-73.988597,43888,Subscriber,1989,1,31
4052921,1334,2020-04-30 23:59:23.6460,2020-05-01 00:21:38.2190,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,36853,Subscriber,1973,1,47
4052922,1334,2020-04-30 23:59:33.6760,2020-05-01 00:21:48.2150,3292,5 Ave & E 93 St,40.785785,-73.957481,509,9 Ave & W 22 St,40.745497,-74.001971,37808,Subscriber,1981,1,39
4052923,234,2020-04-30 23:59:56.9720,2020-05-01 00:03:51.9600,469,Broadway & W 53 St,40.763441,-73.982681,495,W 47 St & 10 Ave,40.762699,-73.993012,20635,Subscriber,1996,2,24
4052924,267,2020-04-30 23:59:59.3510,2020-05-01 00:04:26.8110,3812,University Pl & E 14 St,40.734814,-73.992085,503,E 20 St & Park Ave,40.738274,-73.987520,37530,Subscriber,1980,1,40

In [45]:
trip_df.to_csv(r'April_May_June_CityBikeData.csv', index=False)